language: node_js
node_js:
  - "0.10.29"

before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "npm install -g coffee-script"
  - "npm install -g spacejam"

script: "spacejam test-packages ./"

branches:
  only:
    - master
    - devel
